name: CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with: 
          node-version: 12.x
          
      #instalar as dependencias NPM/YARN
      - name: Install dependencies
        run: yarn 
      
      #EXCUTAR BUILD
      - name: Run build
        run: yarn build
      
      - name: Copy dist to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist"
          target: "test"
      
      
      #SUBSTITUIR O CODIGO EXISTENTE DA PASTA EXISTENTE PELO NOVO CODIGO
      #COPIAR PASTA DIST PARA DENTRO DA DIGITALOCEAN
      #ENTRAR NA DIGITALOCEAN E EXECUTAR YARN
      #eXCUTAR MIGRATIONS DO TYPEORM

      # RESTART NODE SERVER
  
